config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :bookings

  root 'bookings#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking
  include Mongoid::Document

  field :origin_address, type: String
  field :origin_lat, type: Float
  field :origin_lon, type: Float
  field :destiny_address, type: String
  field :destiny_lat, type: Float
  field :destiny_lon, type: Float
  field :service_id, type: String
  field :status, type: Integer
  field :assigned_driver, type: Boolean

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
require 'json'
require 'httparty'

class BookingsController < ApplicationController
  include HTTParty
  before_action :set_booking, only: [:show, :update, :destroy]

  TOKEN = 'ccRtcEaHTyfRUu-5_GgOCADWVxcfaTfORqDwYLseZ-rJ_WsM-hjgDw'
  @base_uri = "https://sandbox.picap.co/api/:url?t=#{TOKEN}"

  # GET /bookings
  def index
    @bookings = Booking.all
  end

  # GET //bookings/
  def new
    @booking = Booking.new
  end

  # GET /bookings/1
  def show; end

  # POST /bookings
  def create
    base_uri = "https://sandbox.picap.co/api/third/bookings?t=#{TOKEN}"
    create_request = {
      "booking":{
          "address": booking_params[:origin_address],
          "lat": booking_params[:origin_lat],
          "lon": booking_params[:origin_lon],
          "requested_service_type_id": "5c71b03a58b9ba10fa6393cf",
          "return_to_origin": false,
          "requires_a_driver_with_base_money": false,
          "stops":[
            {
                "address": booking_params[:destiny_address],
                "lat": booking_params[:destiny_lat],
                "lon": booking_params[:destiny_lon],
                "packages":[
                  {
                      "indications": "Indicaciones",
                      "declared_value": {
                        "sub_units": 210000,
                        "currency": "COP"
                      },
                      "reference": "Pedido 1",
                      "counter_delivery": false,
                      "size_cd": 1
                  }
                ]
            }
          ]
      }
    }

    response = HTTParty.post( base_uri, 
    :body => 
      create_request.to_json,
    :headers => { 'Content-Type' => 'application/json' } )

    @booking = Booking.create(booking_params)
    @booking.update(service_id: response["_id"], status: response["status_cd"], assigned_driver: response["driver"] ? 1 : 0 )

    render json: @booking
  end

  # PATCH/PUT /bookings/1
  def update
    base_uri = "https://sandbox.picap.co/api/third/bookings/#{@booking.service_id}/cancel?t=#{TOKEN}"

    response = HTTParty.patch(base_uri, 
    :headers => { 'Content-Type' => 'application/json' } )

    render :show
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy
  end

  private

    def booking_params
      params.require(:booking).permit(:origin_address, :origin_lat, :origin_lon, :destiny_address, :destiny_lat, :destiny_lon)
    end  

    def set_booking
      @booking = Booking.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_controller_helper.rb
module BookingControllerHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/index.html.erb
<ul>
  <% @bookings.each do |booking| %> 

      <li>
        <div>booking id: <%= booking.service_id %></div>
        <div>direccion de origen: <%= booking.origin_address %></div>
        <div>direccion de envio: <%= booking.destiny_address %></div>
      </li>
      <button><%= link_to 'Ver detalle del servicio', booking_path(booking.id) %></button>
    <% end %>

</ul>

app/views/bookings/new.html.erb
<%= simple_form_for @booking do |f| %>
  <%= f.input :origin_address %>
  <%= f.input :origin_lat %>
  <%= f.input :origin_lon %>
  <%= f.input :destiny_address %>
  <%= f.input :destiny_lat %>
  <%= f.input :destiny_lon %>
  <%= f.button :submit %>
<% end %>

<button><%= link_to 'Ver listado de servicios', bookings_path %></button>

app/views/bookings/show.html.erb
<h3><%= "Detalle de Booking Nº #{@booking.id}" %></h3>

<div>direccion de origen: <%= @booking.origin_address %></div>
<div>direccion de envio: <%= @booking.destiny_address %></div>
<div>estado del servicio: <%= @booking.status %></div>
<div>se asigno conductor?: <%= @booking.assigned_driver ? "yes" : "no" %></div>

<button><%= link_to 'Cancelar servicio?', booking_path(@booking.id) %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InitialProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>